version: '2.4'
services:
  mysql:
    restart: 'no'
    container_name: hkserver-mysql
    ports:
      - "3306:3306"
    extends:
        file: build/docker-compose.common.yml
        service: mysql
  postgres:
    restart: 'no'
    container_name: hkserver-postgres
    ports:
      - "5432:5432"
    extends:
        file: build/docker-compose.common.yml
        service: postgres
  minio:
    restart: 'no'
    container_name: hkserver-minio
    ports:
      - "9001:9000"
    extends:
        file: build/docker-compose.common.yml
        service: minio
  inbucket:
    restart: 'no'
    container_name: hkserver-inbucket
    ports:
      - "20025:10025"
      - "20080:10080"
      - "20110:10110"
    extends:
        file: build/docker-compose.common.yml
        service: inbucket
  openldap:
    restart: 'no'
    container_name: hkserver-openldap
    ports:
      - "389:389"
      - "636:636"
    extends:
        file: build/docker-compose.common.yml
        service: openldap
  elasticsearch:
    restart: 'no'
    container_name: hkserver-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    extends:
        file: build/docker-compose.common.yml
        service: elasticsearch
  dejavu:
    restart: 'no'
    container_name: hkserver-dejavu
    ports:
      - "1358:1358"
    extends:
        file: build/docker-compose.common.yml
        service: dejavu
  keycloak:
    restart: 'no'
    container_name: hkserver-saml
    ports:
      - "8484:8080"
    extends:
        file: build/docker-compose.common.yml
        service: keycloak

networks:
  hk-test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.254.0/24
          ip_range: 192.168.254.0/24
